[2025-09-25 23:00:03,147: INFO: main: Starting the CNN CD Application]
[2025-09-25 23:01:09,596: INFO: main: Starting the CNN CD Application]
[2025-09-25 23:01:09,596: INFO: main: Starting the CNN CD Application at 2nd time]
[2025-10-04 19:53:42,018: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-10-04 19:53:42,022: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 19:53:42,023: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 19:53:42,024: INFO: common: created directory at: artifacts]
[2025-10-04 19:53:42,027: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 19:53:42,061: INFO: transport: Attempting refresh to obtain initial access_token]
[2025-10-04 19:53:42,070: INFO: client: Refreshing access_token]
[2025-10-04 19:53:47,613: ERROR: main: [Errno 2] No such file or directory: 'Downloaded_Folder/Chicken-fecal-images.zip']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_o1_data_ingestion.py", line 24, in main
    raise e
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_o1_data_ingestion.py", line 19, in main
    data_ingestion.download_folder()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 50, in download_folder
    file.GetContentFile(self.config.local_data_file)  # overwrite path
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\pydrive2\auth.py", line 85, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\pydrive2\files.py", line 336, in GetContentFile
    with open(filename, mode="w+b") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'Downloaded_Folder/Chicken-fecal-images.zip'
[2025-10-04 19:57:43,888: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-10-04 19:57:43,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 19:57:43,909: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 19:57:43,911: INFO: common: created directory at: artifacts]
[2025-10-04 19:57:43,912: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 19:57:43,913: ERROR: main: [Errno 2] No such file or directory: 'C:/Users/dmsum/OneDrive/Desktop/.../client_secrets.json']
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    data_ingestion.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_o1_data_ingestion.py", line 24, in main
    raise e
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_o1_data_ingestion.py", line 17, in main
    data_ingestion = DataIngestion(config=data_ingestion_config)
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 16, in __init__
    self.drive = self._authenticate()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 20, in _authenticate
    credentials = ServiceAccountCredentials.from_json_keyfile_name(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\oauth2client\service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/dmsum/OneDrive/Desktop/.../client_secrets.json'
[2025-10-04 19:59:20,197: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-10-04 19:59:20,217: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-04 19:59:20,221: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-04 19:59:20,221: INFO: common: created directory at: artifacts]
[2025-10-04 19:59:20,222: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-04 19:59:20,260: INFO: transport: Attempting refresh to obtain initial access_token]
[2025-10-04 19:59:20,271: INFO: client: Refreshing access_token]
[2025-10-04 20:01:39,414: INFO: main: >>>>> stage Data Ingestion Stage completed <<<<<

x========x]
[2025-10-05 22:33:42,314: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-10-05 22:33:42,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-05 22:33:42,322: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-05 22:33:42,323: INFO: common: created directory at: artifacts]
[2025-10-05 22:33:42,324: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-05 22:33:42,361: INFO: transport: Attempting refresh to obtain initial access_token]
[2025-10-05 22:33:42,374: INFO: client: Refreshing access_token]
[2025-10-05 22:34:10,214: INFO: main: >>>>> stage Data Ingestion Stage started <<<<<]
[2025-10-05 22:34:10,218: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-05 22:34:10,220: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-05 22:34:10,220: INFO: common: created directory at: artifacts]
[2025-10-05 22:34:10,222: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-05 22:34:10,242: INFO: transport: Attempting refresh to obtain initial access_token]
[2025-10-05 22:34:10,249: INFO: client: Refreshing access_token]
[2025-10-05 22:34:12,619: INFO: client: Failed to retrieve access token: {"error":"invalid_grant","error_description":"Invalid JWT Signature."}]
[2025-10-05 22:34:12,619: ERROR: main: invalid_grant: Invalid JWT Signature.]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    data_ingestion.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 24, in main
    raise e
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 19, in main
    data_ingestion.download_folder()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\data_ingestion.py", line 40, in download_folder
    file_list = self.drive.ListFile(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\pydrive2\apiattr.py", line 166, in GetList
    for x in self:
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\pydrive2\apiattr.py", line 150, in __next__
    result = self._GetList()
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\pydrive2\auth.py", line 85, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\pydrive2\files.py", line 84, in _GetList
    self.auth.service.files()
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\oauth2client\client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Invalid JWT Signature.
[2025-10-05 22:35:54,471: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-05 22:35:54,476: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-05 22:35:54,479: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-05 22:35:54,479: INFO: common: created directory at: artifacts]
[2025-10-05 22:35:54,480: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-05 22:35:55,348: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-05 22:36:00,815: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-05 22:36:51,621: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-05 22:36:51,625: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-05 22:36:51,627: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-05 22:36:51,627: INFO: common: created directory at: artifacts]
[2025-10-05 22:36:51,629: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-05 22:36:52,299: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-05 22:36:52,658: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-09 20:33:12,406: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 20:33:12,430: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 20:33:12,432: INFO: common: created directory at: artifacts]
[2025-10-09 20:36:03,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 20:36:03,301: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 20:36:03,303: INFO: common: created directory at: artifacts]
[2025-10-09 20:36:03,307: INFO: common: created directory at: artifacts\training]
[2025-10-09 20:42:05,312: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-09 20:42:05,318: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 20:42:05,322: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 20:42:05,322: INFO: common: created directory at: artifacts]
[2025-10-09 20:42:05,323: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-09 20:42:06,247: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 20:42:09,411: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-09 20:42:23,816: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 20:42:23,831: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 20:42:23,837: INFO: common: created directory at: artifacts]
[2025-10-09 20:42:23,843: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:03:03,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:03:03,067: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:03:03,071: INFO: common: created directory at: artifacts]
[2025-10-09 21:03:03,076: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:05:23,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:05:24,003: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:05:24,006: INFO: common: created directory at: artifacts]
[2025-10-09 21:05:24,008: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:08:30,529: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:08:30,534: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:08:30,537: INFO: common: created directory at: artifacts]
[2025-10-09 21:08:30,542: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:11:13,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:11:13,399: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:11:13,406: INFO: common: created directory at: artifacts]
[2025-10-09 21:11:13,412: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:11:56,016: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:11:56,021: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:11:56,023: INFO: common: created directory at: artifacts]
[2025-10-09 21:11:56,025: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:18:28,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:18:28,446: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:18:28,454: INFO: common: created directory at: artifacts]
[2025-10-09 21:18:28,465: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:23:02,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:23:02,442: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:23:02,445: INFO: common: created directory at: artifacts]
[2025-10-09 21:23:02,449: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:41:06,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:41:06,136: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:41:06,141: INFO: common: created directory at: artifacts]
[2025-10-09 21:41:06,144: INFO: common: created directory at: artifacts\training]
[2025-10-09 21:53:21,663: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-09 21:53:21,674: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:53:21,682: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:53:21,695: INFO: common: created directory at: artifacts]
[2025-10-09 21:53:21,696: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-09 21:53:23,581: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 21:53:26,968: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-09 21:53:26,968: INFO: main: *******************]
[2025-10-09 21:53:26,968: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-10-09 21:53:26,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 21:53:26,982: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 21:53:26,984: INFO: common: created directory at: artifacts]
[2025-10-09 21:53:26,984: ERROR: main: 'ConfigurationManager' object has no attribute 'get_training_config']
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    model_trainer.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_03_model_trainer.py", line 15, in main
    training_config = config.get_training_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_training_config'
[2025-10-09 22:00:29,164: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-09 22:00:29,169: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:00:29,171: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:00:29,173: INFO: common: created directory at: artifacts]
[2025-10-09 22:00:29,173: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-09 22:00:29,857: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 22:00:34,225: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-09 22:00:34,225: INFO: main: *******************]
[2025-10-09 22:00:34,225: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-10-09 22:00:34,232: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:00:34,234: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:00:34,235: INFO: common: created directory at: artifacts]
[2025-10-09 22:00:34,235: INFO: common: created directory at: artifacts\training]
[2025-10-09 22:11:23,873: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-10-09 22:19:02,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:19:02,077: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:19:02,080: INFO: common: created directory at: artifacts]
[2025-10-09 22:22:06,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:22:06,220: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:22:06,222: INFO: common: created directory at: artifacts]
[2025-10-09 22:25:25,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:25:25,172: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:25:25,174: INFO: common: created directory at: artifacts]
[2025-10-09 22:31:00,440: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-09 22:31:00,445: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:31:00,449: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:31:00,450: INFO: common: created directory at: artifacts]
[2025-10-09 22:31:00,450: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    prepare_base_model.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2025-10-09 22:31:55,510: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-09 22:31:55,514: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:31:55,517: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:31:55,518: INFO: common: created directory at: artifacts]
[2025-10-09 22:31:55,519: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-09 22:31:56,244: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-09 22:31:56,552: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-09 22:31:56,552: INFO: main: *******************]
[2025-10-09 22:31:56,552: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-10-09 22:31:56,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:31:56,560: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:31:56,561: INFO: common: created directory at: artifacts]
[2025-10-09 22:31:56,562: INFO: common: created directory at: artifacts\training]
[2025-10-09 22:41:01,347: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-10-09 22:41:01,352: INFO: main: *******************]
[2025-10-09 22:41:01,353: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-10-09 22:41:01,371: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-09 22:41:01,397: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-09 22:41:01,399: INFO: common: created directory at: artifacts]
[2025-10-09 22:41:07,853: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/Chicken-fecal-images']
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    model_evalution.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_04_evaluation.py", line 19, in main
    evaluation.evaluation()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\evaluation.py", line 45, in evaluation
    self._valid_generator()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\evaluation.py", line 30, in _valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/Chicken-fecal-images'
[2025-10-15 22:01:12,405: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.101:8080]
[2025-10-15 22:01:12,406: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-10-15 22:01:12,414: INFO: _internal:  * Restarting with stat]
[2025-10-15 22:01:20,420: WARNING: _internal:  * Debugger is active!]
[2025-10-15 22:01:20,429: INFO: _internal:  * Debugger PIN: 781-048-057]
[2025-10-15 22:01:38,168: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:01:38] "GET / HTTP/1.1" 200 -]
[2025-10-15 22:03:59,456: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.101:8080]
[2025-10-15 22:03:59,457: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-10-15 22:03:59,459: INFO: _internal:  * Restarting with stat]
[2025-10-15 22:04:06,644: WARNING: _internal:  * Debugger is active!]
[2025-10-15 22:04:06,652: INFO: _internal:  * Debugger PIN: 781-048-057]
[2025-10-15 22:04:06,705: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:04:06] "GET / HTTP/1.1" 200 -]
[2025-10-15 22:04:35,154: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:04:35] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:05:15,609: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:05:15] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:05:20,961: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:05:20] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:05:41,078: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:05:41] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:05:46,560: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000236974923A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-10-15 22:05:46,565: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:05:46] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:05:53,417: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x00000236974920D0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-10-15 22:05:53,423: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:05:53] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:06:57,133: INFO: main: >>>>> stage Prepare base model started <<<<<]
[2025-10-15 22:06:57,184: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-15 22:06:57,203: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-15 22:06:57,206: INFO: common: created directory at: artifacts]
[2025-10-15 22:06:57,206: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-10-15 22:06:58,078: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-10-15 22:07:00,946: INFO: main: >>>>> stage Prepare base model completed <<<<<

x========x]
[2025-10-15 22:07:00,946: INFO: main: *******************]
[2025-10-15 22:07:00,946: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-10-15 22:07:00,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-15 22:07:00,956: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-15 22:07:00,958: INFO: common: created directory at: artifacts]
[2025-10-15 22:07:00,959: INFO: common: created directory at: artifacts\training]
[2025-10-15 22:08:37,957: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:08:37] "GET / HTTP/1.1" 200 -]
[2025-10-15 22:08:49,749: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:08:49] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:16:37,254: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-10-15 22:16:37,254: INFO: main: *******************]
[2025-10-15 22:16:37,254: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-10-15 22:16:37,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-15 22:16:37,276: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-15 22:16:37,280: INFO: common: created directory at: artifacts]
[2025-10-15 22:16:41,772: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/Chicken-fecal-images']
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    model_evalution.main()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\pipeline\stage_04_evaluation.py", line 19, in main
    evaluation.evaluation()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\evaluation.py", line 45, in evaluation
    self._valid_generator()
  File "c:\users\dmsum\onedrive\desktop\end-to-end-deep-learning-project-chicken-disease-classification\src\cnnClassifier\components\evaluation.py", line 30, in _valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\dmsum\anaconda3\envs\cnncd\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts/data_ingestion/Chicken-fecal-images'
[2025-10-15 22:16:42,770: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:16:42] "GET /train HTTP/1.1" 200 -]
[2025-10-15 22:16:56,306: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:16:56] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:17:08,226: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:17:08] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:17:21,611: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:17:21] "POST /predict HTTP/1.1" 200 -]
[2025-10-15 22:25:39,562: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.101:8080]
[2025-10-15 22:25:39,562: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-10-15 22:25:39,567: INFO: _internal:  * Restarting with stat]
[2025-10-15 22:25:46,412: WARNING: _internal:  * Debugger is active!]
[2025-10-15 22:25:46,419: INFO: _internal:  * Debugger PIN: 781-048-057]
[2025-10-15 22:25:48,750: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:25:48] "GET / HTTP/1.1" 200 -]
[2025-10-15 22:25:59,334: INFO: _internal: 127.0.0.1 - - [15/Oct/2025 22:25:59] "POST /predict HTTP/1.1" 200 -]
